### ISSUE TITLE
usage of array id numbers

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#10]
@rvernica 

Follow up question from internal ticket https://paradigm4.atlassian.net/browse/SDB-5165.

Does `secure_scan` mechanism involve array id numbers maintained in Postgres system catalog? ... these might not be preserved across scidb_backup.py save and restore.

I guess not, but thought I would confirm.

**Comment by rvernica** [comment]
The only hard-coded values are:
* permissions namespace
* permissions array
* user and permission dimensions
* read permission

They are all hard-coded as strings, [here](https://github.com/Paradigm4/secure_scan/blob/master/src/settings.h)

Otherwise the operator is stateless.

So, I don't think changes in array id numbers maintained in Postgres would affect the operator.

**Comment by ksens** [comment]
OK, closing the issue.
