### ISSUE TITLE
as scidbadmin or user with read access to namespace, secure_scan should return all the data

### ISSUE THREAD

**Issue by ksens** [Paradigm4/secure_scan#7]
While deploying `secure_scan` at a customer, the following requirement came to mind: 

When running as scidbadmin, `secure_scan` should always return all the data, i.e. if the logged in user is scidbadmin, the code should bypass looking up the permissions array, and return all the data in the array. 

Also this eases development and testing. 

Having permissions stored for scidbadmin in a permissions array, does not make sense. In this regard, it might make sense to not allow `user_id=1` values in the permissions array (it appears `scidbadmin` is always at `user_id` 1).

**Comment by ksens** [comment]
@mjl-p4

This seems like a logical requirement right? 

I am thinking of adding a code branch here
https://github.com/Paradigm4/secure_scan/blob/master/src/PhysicalSecureScan.cpp#L98

Questions for you:
1. Is it guaranteed that `scidbadmin` will always have `user_id=1`
2. Otherwise, is `scidbadmin` guaranteed to always have that name? Or is there any other mechanism to know that the current user is `scidbadmin`?

**Comment by mjl-p4** [comment]
User id 1 is indeed reserved for the scidbadmin user.  However, users assigned to the "admin" role are also supposed to get all DBA privileges, so you need to do some extra work to to find out if a non-scidbadmin user has admin privileges.   Since it involves Postgres queries, I suggest doing this work in the logical operator rather than at PhysicalFoo::execute() time, so that you only have to do it once.  You then need to communicate what you found out in the logical op to the physical op so you can act on it; the way to do that is with "inspectable cookies", a way for the many physical ops to learn things computed by the one logical op.

I should probably write a wiki page on both topics.  For now,  I'll just paste some code snippets here and come by to discuss them if you have questions.

First, in your logical op, add the following data member and method definition:

    private:
        std::string _privInfo;

    public:
        std::string getInspectable() override { return _privInfo; }

Usually LogicalFoo::inferAccess() is where you'd put code to say "this op requires such-and-such permissions".  Your case is a little different, because instead of requiring the permissions you just want to know if you have them or not, so you can act differently later on.  To make that happen, put this snippet in LogicalFoo::inferAccess() (it could go in inferSchema() too but may as well keep the access stuff together):

    if (query->getSession()->getUser().isDbAdmin()) {
        // Easy case: it's scidbadmin.  May as well use the well-known DBA_USER
        // string to signal that we have privs.
        _privInfo = rbac::DBA_USER;
    } else {
        // Harder case: need to find out if they are assigned to the "admin" role.
        // Make a temporary Rights object and check to see if we have the rights.
        rbac::Rights neededRights;
        neededRights.upsert(rbac::ET_DB, "", rbac::P_DB_ADMIN);
        try {
            using scidb::namespaces::Communicator::checkAccess;
            checkAccess(query->getSession().get(), &neededRights);
            _privInfo  rbac::DBA_USER;    // Succeeded, user must have the admin role.
        } catch (...) {
            // checkAccess threw, too bad for yew!
        }
    }

Now you have a non-empty _privInfo string if and only if you have admin privileges.  And that string is available via getInspectable(), so your physical op can inspect it.  Set up this plumbing method in your physical op:

    void inspectLogicalOp(LogicalOperator const& lop) override
    {
        setControlCookie(lop.getInspectable());
    }

And now your physical op execute() method can find out whether you have privileges:

    if (getControlCookie() == rbac::DBA_USER) {
        // Do privileged stuff.
    } else {
        // Do ordinary not-so-privileged stuff.
    }

Of course you really only need to check for

    bool gotPrivs = !getControlCookie().empty();

You can pipe any kind of elaborate stringifiaable stuff from logical op to physical op(s) this way, JSON or whatever you need.

Alles klar?

**Comment by ksens** [comment]
@mjl-p4 

After working with `secure_scan` on a customer site, I am now reforming this requirement a bit more. 

In this ticket, I first proposed that folks in scidb admin group should get full read access via `secure_scan`. 

How about we make this more general, and say that when the following is called
```sh
secure_scan(NMSP.array)
```
- anyone with `r` (read) access to namespace `NMSP` or belonging to scidb admin group should get access to the full array
- if `l` (list) access is available, return data after joining with the permissions array (this is the current behavior)
- if none of the above permissions, then error out and return nothing

The reason I am proposing this change is that at the customer site, 
- there would be one person assuming scidb admin
- there would be three or four people who would have access to all the data (the data loaders)

If we have the above capability, then the admin role can be kept separate from the data-loader role. 

What are your thoughts? We can talk about implementation details later.

**Comment by mjl-p4** [comment]
That sounds like the way these permissions currently work, or am I missing something?  We should probably sit down and discuss in person at this point.

**Comment by rvernica** [comment]
I made the changes that Mike suggested in 337c01de6855189af08572e3d271d1679466ebba but things don't fully work.

1. `privInfo` is set correctly
1. `inspectLogicalOp` and `getInspectable` get called
1. But `getControlCookie` returns an empty string.

Am I missing something? Below are the relevant messages printed in the log:
```
2017-12-15 07:23:12,035 [0x7fb1142d6700] [DEBUG]: secure_scan::privInfo:scidbadmin
2017-12-15 07:23:12,062 [0x7fb1144d8700] [DEBUG]: secure_scan::inspectLogicalOp
2017-12-15 07:23:12,062 [0x7fb1144d8700] [DEBUG]: secure_scan::getInspectable
2017-12-15 07:23:12,064 [0x7fb1143d7700] [DEBUG]: secure_scan::userId:1
2017-12-15 07:23:12,065 [0x7fb1143d7700] [DEBUG]: secure_scan::getControlCookie:
```

**Comment by mjl-p4** [comment]
OK, here's what I think's happening.

An unfortunate aspect of our current executor/query processor code is that the friggin' query gets parsed multiple times.  It's ridiculous, it's a PITA, but there it is.  I told you above to put the checking code into inferAcess() because that seemed to make more sense... but I suspect that that method gets called on an early parse, its resulting logical plan tree is thrown away, and then the next parse generates a tree that does _not_ have the \_privInfo string set.

So, move that checking code from inferAccess() to inferSchema() and see if you have better luck.  That's how all the other operators that use this control cookie/inspectable machinery work.  I guess I was overly optimistic about putting access-like things in inferAccess(), and forgot about this kludge in the query processor.

**Comment by rvernica** [comment]
Thanks, Mike! That did the trick.

**Comment by rvernica** [comment]
Reopen this to track the generalization based on user's permissions.

**Comment by rvernica** [comment]
Just to clarify, for the user with `r` permission on the namespace, that user needs also to have `l` permission on the namespace. In the current implementation the `l` permission is checked in `inferAccess` while the `r` permission is checked in `inferSchema` (so that the cookie can be set correctly).

**Comment by rvernica** [comment]
I removed the `l` requirement for users with `r` in 5e5e3055822b03fc21a63d4b5f454e225f76d9a2
